セクション画面の実装(動作確認とれておりません)
y-o777/sche-ctrl pull request #30
Opened 2020-10-23 02:31 UTC by s-a1127

2020-10-23 08:02 UTC, y-o777 commented on zeroschool/src/main/java/com/example/demo/form/SectionForm.java
> +		private String RoundNo;
RoundNoをキャメルケースでroundNoとした方が良いと思います。

2020-10-23 08:08 UTC, y-o777 reviewed
レビューが終わりました。

2020-10-24 15:10 UTC, isimatu0612 requested changes
レビューが一旦終わりました。
最新のmasterを取り込んだ後に動作確認も行います。

2020-10-24 15:10 UTC, isimatu0612 commented on zeroschool/bin/main/templates/section/index.html
> +							<th class="text-center"style="width:10%"bgcolor="khaki">目標日</th>
`style="width:10%"`などは、
cssファイルに分けた方が良いです。
今回は、時間があまりないので修正不要です。

2020-10-24 15:10 UTC, isimatu0612 commented on zeroschool/src/main/java/com/example/demo/repository/SectionRepository.java
>  	 * @return List<SectionEntity>
JavaDocと実際の実装が合っていないの、修正をお願いいたします。

2020-10-24 15:10 UTC, isimatu0612 commented on zeroschool/src/main/java/com/example/demo/entity/SectionEntity.java
> +	//Roundのデータクラス
普通のコメントでなく、
JavaDocで記載するよう修正をお願いします。

2020-10-24 15:10 UTC, isimatu0612 commented on zeroschool/src/main/java/com/example/demo/entity/SectionEntity.java
> +	//Chapterのデータクラス
普通のコメントでなく、
JavaDocで記載するよう修正をお願いします。

2020-10-24 15:10 UTC, isimatu0612 commented on zeroschool/bin/main/templates/section/index.html
>  	<body>
bootstrapの呼び出しの部分も同様です。

2020-10-24 15:26 UTC, isimatu0612 requested changes

2020-10-24 15:26 UTC, isimatu0612 commented on zeroschool/src/main/java/com/example/demo/repository/SectionRepository.java
> +			  sql = "SELECT COURSE_NAME FROM M_COURSES WHERE ID=" + courseId;
分けて取得するにしても、1メソッド内で行うのはあまりよろしくないです。
同じconnection内で行いうのは良いと思います。

2020-10-24 15:26 UTC, isimatu0612 commented on zeroschool/src/main/java/com/example/demo/repository/SectionRepository.java
String sql = "SQL文"のところもtry-catchから出しても良いと思います。

2020-10-25 06:20 UTC, s-a1127 commented on zeroschool/bin/main/templates/section/index.html
>  	<body>
承知いたしました。修正いたします。

2020-10-25 06:21 UTC, s-a1127 commented on zeroschool/bin/main/templates/section/index.html
>          				<button  onclick="location.href='http://localhost:8080/course/index'"style="border:none;outline:none;background-color:transparent;color:white;">戻る</button>
参考サイトまで教えていただきありがとうございます。
修正いたします。

2020-10-25 06:21 UTC, s-a1127 commented on zeroschool/bin/main/templates/section/index.html
> +					    </tr>
ご指摘いただきありがとうございます。
修正いたします。

2020-10-25 06:22 UTC, s-a1127 commented on zeroschool/src/main/java/com/example/demo/form/SectionForm.java
> +	private List<RoundForm> formList;
承知いたしました。ご指摘いただきありがとうございます。
今後命名する際は統一性を留意いたします。

2020-10-25 06:24 UTC, s-a1127 commented on zeroschool/src/main/java/com/example/demo/entity/SectionEntity.java
> +	//Roundのデータクラス
承知いたしました。修正いたします。

2020-10-25 06:24 UTC, s-a1127 commented on zeroschool/src/main/java/com/example/demo/repository/SectionRepository.java
>  	 * @return List<SectionEntity>
失礼いたしました。
修正いたします。

2020-10-25 06:56 UTC, s-a1127 commented on zeroschool/bin/main/templates/section/index.html
> +							<th class="text-center"style="width:10%"bgcolor="khaki">目標日</th>
承知しました。ご指摘いただきありがとうございます。

2020-10-25 06:56 UTC, s-a1127 commented on zeroschool/src/main/java/com/example/demo/entity/SectionEntity.java
> +	//Roundのデータクラス
承知しました、修正いたしました。

2020-10-26 03:26 UTC, closed without merging