セットスケジュール画面レビュー後修正
y-o777/sche-ctrl pull request #33
Opened 2020-10-26 03:27 UTC by y-o777

2020-10-26 06:30 UTC, isimatu0612 requested changes

2020-10-26 06:30 UTC, isimatu0612 commented on zeroschool/src/main/java/com/example/demo/service/SetScheduleService.java
>  			targetDateSetList.add(targetDateSet);
`targetDateSet`の変数名について。
考えすぎかもしれませんが、
`Set<>`というCollectionが存在するので、ややこしいかもしれません。
修正はお任せします。

2020-10-26 08:14 UTC, y-o777 commented on zeroschool/src/main/java/com/example/demo/form/SetScheduleForm.java
>  	@Size(min = 1, max = 45, message = "名前は45字以内で入力してください")
修正いたしました。
エラーメッセージを定数で指定しなければいけないようで
プロパティファイルの記述が増えてしまいました。

2020-10-26 08:15 UTC, y-o777 commented on zeroschool/src/main/java/com/example/demo/service/SetScheduleService.java
>  			targetDateSetList.add(targetDateSet);
今回は適切な名前が思い浮かばないので、このままでよろしくお願いします。

2020-10-26 08:17 UTC, y-o777 commented on zeroschool/src/main/java/com/example/demo/controller/SetScheduleController.java
> +			model.addAttribute("isExistUserId", "そのユーザーIDは既に登録されています");
変更いたしました。

2020-10-26 08:36 UTC, y-o777 commented on zeroschool/src/main/java/com/example/demo/controller/SetScheduleController.java
> +			model.addAttribute("isExistUserId", "そのユーザーIDは既に登録されています");
修正いたしました。

2020-10-26 08:36 UTC, y-o777 commented on zeroschool/src/main/java/com/example/demo/controller/SetScheduleController.java
> +				model.addAttribute("addUserFailed", "ユーザー登録に失敗しました");
修正いたしました。

2020-10-26 08:37 UTC, y-o777 commented on zeroschool/src/main/java/com/example/demo/controller/SetScheduleController.java
> +				model.addAttribute("addTargetDateFailed", "目標日の登録に失敗しました");
修正いたしました。

2020-10-26 22:25 UTC, isimatu0612 commented on zeroschool/src/main/java/com/example/demo/service/SetScheduleService.java
>  			targetDateSetList.add(targetDateSet);
承知いたしました。クローズいたします。

2020-10-26 22:25 UTC, isimatu0612 commented on zeroschool/src/main/java/com/example/demo/controller/SetScheduleController.java
> +			model.addAttribute("isExistUserId", "そのユーザーIDは既に登録されています");
クローズいたします。

2020-10-26 22:25 UTC, isimatu0612 commented on zeroschool/src/main/java/com/example/demo/controller/SetScheduleController.java
> +				model.addAttribute("addTargetDateFailed", "目標日の登録に失敗しました");
クローズいたします。

2020-10-26 22:27 UTC, isimatu0612 commented on zeroschool/src/main/java/com/example/demo/controller/SetScheduleController.java
> +				model.addAttribute("addUserFailed", "ユーザー登録に失敗しました");
クローズいたします。

2020-10-26 22:27 UTC, isimatu0612 commented on zeroschool/src/main/java/com/example/demo/controller/SetScheduleController.java
> +			model.addAttribute("isExistUserId", "そのユーザーIDは既に登録されています");
クローズいたします。

2020-10-26 22:30 UTC, isimatu0612 commented on zeroschool/src/main/java/com/example/demo/form/SetScheduleForm.java
>  	@Size(min = 1, max = 45, message = "名前は45字以内で入力してください")
ありとうございます。
クローズいたします。

2020-10-26 22:33 UTC, isimatu0612 commented on zeroschool/src/main/java/com/example/demo/form/SetScheduleForm.java
>  	@Size(min = 1, max = 45, message = "名前は45字以内で入力してください")
ValidationMessages.propertiesを作る方法でも行けたんですね。

修正ありがとうございます。
クローズいたします。

2020-10-26 22:51 UTC, isimatu0612 requested changes

2020-10-26 22:51 UTC, isimatu0612 commented on zeroschool/src/main/java/com/example/demo/controller/SetScheduleController.java
> +	MessageSource messageSource;
private の付与をお願いします。

2020-10-26 22:51 UTC, isimatu0612 commented on zeroschool/src/main/java/com/example/demo/controller/SetScheduleController.java
> +				// ユーザー登録失敗のためエラーメッセｰジを表示
目標日登録失敗時かと思いますので、
コメントの修正をお願いします。

2020-10-26 22:51 UTC, isimatu0612 commented on zeroschool/src/main/java/com/example/demo/form/SetScheduleForm.java
> +	MessageSource messageSource;
私の知識不足ですが、
こちらは必要そうですか？

2020-10-26 22:51 UTC, isimatu0612 commented on zeroschool/src/main/java/com/example/demo/service/SetScheduleService.java
> +		return setscheRepository.addTargetDate(targetDateSetList);
`setscheRepository`
キャメルに修正をお願いします。

2020-10-26 22:51 UTC, isimatu0612 commented on zeroschool/src/main/java/com/example/demo/controller/SetScheduleController.java
>  			List<String> attendDayList = service.setAttendDay(setScheduleForm);
ユーザー登録失敗時に無駄になるのと、
`attendDayList`を使用しているのが、83行目なので、
81行目あたりに移動をお願いします。

2020-10-27 00:35 UTC, y-o777 commented on zeroschool/src/main/java/com/example/demo/controller/SetScheduleController.java
> +				// ユーザー登録失敗のためエラーメッセｰジを表示
修正いたしました。

2020-10-27 00:36 UTC, y-o777 commented on zeroschool/src/main/java/com/example/demo/controller/SetScheduleController.java
>  			List<String> attendDayList = service.setAttendDay(setScheduleForm);
修正いたしました。

2020-10-27 00:40 UTC, y-o777 commented on zeroschool/src/main/java/com/example/demo/service/SetScheduleService.java
> +		return setscheRepository.addTargetDate(targetDateSetList);
修正いたしました。

2020-10-27 00:41 UTC, y-o777 commented on zeroschool/src/main/java/com/example/demo/controller/SetScheduleController.java
> +	MessageSource messageSource;
修正いたしました。

2020-10-27 00:43 UTC, y-o777 commented on zeroschool/src/main/java/com/example/demo/form/SetScheduleForm.java
> +	MessageSource messageSource;
私も知識不足でした。
コメントアウトして動作確認したところ、正常に動作したので
必要ないと思います。
削除いたしました。

2020-10-27 02:32 UTC, isimatu0612 commented on zeroschool/src/main/java/com/example/demo/controller/SetScheduleController.java
> +	MessageSource messageSource;
ありがとうございます。
クローズいたします。

2020-10-27 02:32 UTC, isimatu0612 commented on zeroschool/src/main/java/com/example/demo/service/SetScheduleService.java
> +		return setscheRepository.addTargetDate(targetDateSetList);
ありがとうございます。
クローズいたします。

2020-10-27 02:32 UTC, isimatu0612 commented on zeroschool/src/main/java/com/example/demo/controller/SetScheduleController.java
>  			List<String> attendDayList = service.setAttendDay(setScheduleForm);
ありがとうございます。
クローズいたします。

2020-10-27 02:33 UTC, isimatu0612 commented on zeroschool/src/main/java/com/example/demo/form/SetScheduleForm.java
> +	MessageSource messageSource;
ありがとうございます。
クローズいたします。

2020-10-27 02:33 UTC, isimatu0612 commented on zeroschool/src/main/java/com/example/demo/controller/SetScheduleController.java
> +				// ユーザー登録失敗のためエラーメッセｰジを表示
ありがとうございます。
クローズいたします。

2020-10-27 02:37 UTC, merged