レビューを基に各ファイルを修正いたしました。
y-o777/sche-ctrl pull request #34
Opened 2020-10-26 07:43 UTC by s-a1127

2020-10-26 07:50 UTC, s-a1127 commented on zeroschool/src/main/java/com/example/demo/controller/SectionController.java
> +		Integer courseId=1;
動作確認のための記述となりますが、
実際は下記の記述となります。
プルリク前に訂正しておらず申し訳ありません。
Integer courseId= form.getCourseId();
String userNo = form.getUserNo();

2020-10-26 09:24 UTC, isimatu0612 requested changes

2020-10-26 09:24 UTC, isimatu0612 commented on zeroschool/src/main/java/com/example/demo/repository/SectionRepository.java
> +		  }
ResultSetのクローズ処理も追加をお願いします。
実装方法は、大野さんや私の実装している物をご覧ください。

2020-10-26 09:24 UTC, isimatu0612 commented on zeroschool/src/main/java/com/example/demo/repository/SectionRepository.java
> +			  sql += " AND a.M_CHPATER_ID = b.M_CHAPTER_ID JOIN dbo.M_COURSES d ON d.ID = C.M_COURSE_ID WHERE b.USER_NO = '"+userNo+"' AND d.ID = "+courseId;
試していないので、確証はありませんが、
このSQLの生成方法は、SQLインジェクション の可能性があります。
pstmt.setString()を使うと防げたはずです。

courseIdやuserNo部分に「user'; DROP TABLE 〜 ;--」
のようなものが入るとテーブルが消える可能性があります。

2020-10-26 09:24 UTC, isimatu0612 commented on zeroschool/src/main/java/com/example/demo/form/SectionForm.java
> +	@NotBlank(message="実施日を選択してください")
エラーメッセージを
プロパティファイルから取得するようになるので、
大野さんのプルリクがmasterに入り次第修正をお願いします。

[大野さんがプルリク中のブランチ](https://github.com/y-o777/sche-ctrl/pull/33/files)

2020-10-26 09:24 UTC, isimatu0612 commented on zeroschool/src/main/java/com/example/demo/repository/SectionRepository.java
> +			  sql += " AND a.M_CHPATER_ID = b.M_CHAPTER_ID JOIN dbo.M_COURSES d ON d.ID = C.M_COURSE_ID WHERE b.USER_NO = '"+userNo+"' AND d.ID = "+courseId;
もしくは、大野さんのFormクラスの実装のように、正規表現チェックの追加をお願いします。

2020-10-26 23:55 UTC, isimatu0612 requested changes

2020-10-26 23:55 UTC, isimatu0612 commented on zeroschool/src/main/java/com/example/demo/repository/SectionRepository.java
> +			  sql += " AND a.M_CHPATER_ID = b.M_CHAPTER_ID JOIN dbo.M_COURSES d ON d.ID = C.M_COURSE_ID WHERE b.USER_NO = '"+userNo+"' AND d.ID = "+courseId;
`JOIN dbo.M_COURSES d ON d.ID = C.M_COURSE_ID WHERE`
↓
`JOIN dbo.M_COURSES d ON d.ID = c.M_COURSE_ID WHERE`
cは小文字かと思います。

2020-10-26 23:55 UTC, isimatu0612 commented on zeroschool/src/main/java/com/example/demo/repository/SectionRepository.java
> +				  }
実装者によって意見がことなりそうな問題ですが、
個人的にこの加工処理は、Serviceで行った方が良いと思いました。
修正はお任せします。

2020-10-26 23:55 UTC, isimatu0612 commented on zeroschool/src/main/java/com/example/demo/service/SectionService.java
> +			RoundForm roundForm = form.getRoundList().get(i);
ここで、エラーが出ます。
`BeanUtilsWrapper.copyProperties(form, entity);`
でListをコピーするのがよろしくなさそうです。

2020-10-26 23:55 UTC, isimatu0612 commented on zeroschool/src/main/resources/templates/section/index.html
> +							<th class="text-center"style="width:10%"th:if="${chapterform.implementationTime != null}"th:text="${chapterform.implementationTime}"></th>
下の方で、`${string.isEmpty()}`を使用しているので、
こちらも同じように修正をお願いします。

`th:unless`で否定形にできます

2020-10-26 23:55 UTC, isimatu0612 commented on zeroschool/src/main/resources/templates/section/index.html
> +        				<button  onclick="location.href='@{/course/index.html}'"style="border:none;outline:none;background-color:transparent;color:white;">戻る</button>
・index.htmlを直接呼ぶのでなく、
Controllerの`@RequestMapping("/course")`に飛ぶように修正をお願いします。

・`onclick`　→ `th:onclick`

[参考URL](https://stackoverrun.com/ja/q/13014702)

2020-10-26 23:55 UTC, isimatu0612 commented on zeroschool/src/main/resources/templates/section/index.html
> +							<td style="color:red;" th:text="${error}"></td>
全体的にですが、
見た目の統一のためのBootStrap採用ですので、
基本、BootStrapを使った方が良いです。

修正は不要です。

2020-10-26 23:55 UTC, isimatu0612 commented on zeroschool/src/main/resources/templates/section/index.html
> +						<tr th:if="${validationError}" th:each="error : ${validationError}">
`th:if="${validationError}"`
Listのnullチェック・サイズチェックは、ユーティリティーメソッドを使うよう修正をお願いします。

2020-10-26 23:55 UTC, isimatu0612 commented on zeroschool/src/main/resources/templates/section/index.html
> +						<tr th:if="${validationError}" th:each="error : ${validationError}">
ちなみにですが、以下のような書き方では実装は難しそうでしたか？
Controllerでリストに詰め直す必要がないかもしれません。

`th:if="${#fields.hasErrors('name')}"  th:errors="*{name}"`

2020-10-26 23:56 UTC, isimatu0612 commented
全体的にインデントがバラバラなので、
Eclipseで保管時アクションのオートフォーマットを有効にするか、
「ctr + shift + f」の徹底をお願いいたします。

2020-10-27 00:40 UTC, s-a1127 commented on zeroschool/src/main/java/com/example/demo/controller/SectionController.java
> +		Integer courseId=1;
承知いたしました。
①の取得方法で修正いたします。

2020-10-27 00:40 UTC, s-a1127 commented on zeroschool/src/main/java/com/example/demo/controller/SectionController.java
>  	MessageSource messageSource;
承知いたしました。

2020-10-27 00:41 UTC, s-a1127 commented on zeroschool/src/main/java/com/example/demo/controller/SectionController.java
> +	public ModelAndView get(@ModelAttribute SectionForm form, ModelAndView model) {
承知いたしました。ご指摘いただきありがとうございます。

2020-10-27 00:42 UTC, s-a1127 commented on zeroschool/src/main/java/com/example/demo/controller/SectionController.java
> +		List<RoundForm> roundList = new ArrayList<RoundForm>();
教えていただきありがとうございます。
修正いたします。

2020-10-27 00:43 UTC, s-a1127 commented on zeroschool/src/main/java/com/example/demo/service/SectionService.java
> +		for(int i = 0;i < form.getRoundList().size();i++) {
失礼しました。
ctr + shift + fを徹底いたします。

2020-10-27 00:46 UTC, s-a1127 commented on zeroschool/src/main/java/com/example/demo/service/SectionService.java
> +			roundList.set(i,roundForm);
ソースを確認しましたが、私の勘違いでした。
ご指摘どおり修正いたします。

2020-10-27 00:47 UTC, s-a1127 commented on zeroschool/src/main/java/com/example/demo/repository/SectionRepository.java
> +		  }
承知しました。
大野さんのプルリクを拝見しておりましたが、
実装時に失念しておりました。申し訳ございません。

2020-10-27 00:48 UTC, s-a1127 commented on zeroschool/src/main/java/com/example/demo/repository/SectionRepository.java
> +			  sql += " AND a.M_CHPATER_ID = b.M_CHAPTER_ID JOIN dbo.M_COURSES d ON d.ID = C.M_COURSE_ID WHERE b.USER_NO = '"+userNo+"' AND d.ID = "+courseId;
ご指摘いただきありがとうございます。
大野さんのソースを参考にしながら調査し修正いたします。

2020-10-27 00:49 UTC, s-a1127 commented on zeroschool/src/main/java/com/example/demo/form/SectionForm.java
> +	@NotBlank(message="実施日を選択してください")
承知いたしました。

2020-10-27 00:49 UTC, s-a1127 commented on zeroschool/src/main/java/com/example/demo/repository/SectionRepository.java
> +			  sql += " AND a.M_CHPATER_ID = b.M_CHAPTER_ID JOIN dbo.M_COURSES d ON d.ID = C.M_COURSE_ID WHERE b.USER_NO = '"+userNo+"' AND d.ID = "+courseId;
ご指摘いただきありがとうございます。修正いたします。

2020-10-27 00:50 UTC, s-a1127 commented on zeroschool/src/main/java/com/example/demo/repository/SectionRepository.java
> +				  }
ご指摘いただきありがとうございます。
こちらの修正はとりあえず後回しにし、時間があれば修正させていただきます。

2020-10-27 00:52 UTC, s-a1127 commented on zeroschool/src/main/java/com/example/demo/service/SectionService.java
> +			RoundForm roundForm = form.getRoundList().get(i);
chapterデータのインナークラスとRoundデータのインナークラスを
それぞれインスタンス化し、リストの中身をコピーさせる記述に修正しました。

2020-10-27 00:52 UTC, s-a1127 commented on zeroschool/src/main/resources/templates/section/index.html
> +							<th class="text-center"style="width:10%"th:if="${chapterform.implementationTime != null}"th:text="${chapterform.implementationTime}"></th>
承知いたしました。
教えていただきありがとうございます。

2020-10-27 00:53 UTC, s-a1127 commented on zeroschool/src/main/resources/templates/section/index.html
> +        				<button  onclick="location.href='@{/course/index.html}'"style="border:none;outline:none;background-color:transparent;color:white;">戻る</button>
承知しました。修正いたします。

2020-10-27 00:54 UTC, s-a1127 commented on zeroschool/src/main/resources/templates/section/index.html
> +							<td style="color:red;" th:text="${error}"></td>
ご指摘いただきありがとうございます。以後意識して実装いたします。

2020-10-27 00:56 UTC, s-a1127 commented on zeroschool/src/main/resources/templates/section/index.html
> +						<tr th:if="${validationError}" th:each="error : ${validationError}">
難しくはないです！
参考にしたサイトにこの方法があったので試してみました。

2020-10-28 02:13 UTC, isimatu0612 requested changes

2020-10-28 02:13 UTC, isimatu0612 commented on zeroschool/src/main/java/com/example/demo/controller/SectionController.java
> +	@PostMapping("/post")
URLでpostのみはあまり見ないです。
他の画面でもpostがあるため。

せめて
`/section/index/post`

ちなみに`@RequestMapping(/section/index)`とし
`@PostMapping(param="add")`とすれば、
`/section/index?add`というURLになります。

または、`@PostMapping("add")`
で`/section/index/add`になるはずです。

2020-10-28 02:40 UTC, s-a1127 commented on zeroschool/src/main/java/com/example/demo/controller/SectionController.java
>  @Controller
大変失礼しました。
各クラスのJavaDocを記載しました。

2020-10-28 05:48 UTC, y-o777 reviewed
コード拝見させていただきました。
私からの指摘はございません。

2020-10-28 09:24 UTC, isimatu0612 requested changes

2020-10-28 09:24 UTC, isimatu0612 commented on zeroschool/src/main/java/com/example/demo/controller/SectionController.java
>  @Controller
ありがとうございます。
クローズいたします。

2020-10-28 09:24 UTC, isimatu0612 commented on zeroschool/src/main/java/com/example/demo/repository/SectionRepository.java
> +			// ROundNoを初期化
`ROundNo`→`RoundNo`でお願いします。
バグ修正の時に覚えていたらで大丈夫です。

2020-10-28 09:24 UTC, isimatu0612 commented on zeroschool/src/main/java/com/example/demo/entity/SectionEntity.java
> +	 * chapterデータのインナークラス
ChapterData自体がインナークラスなので、
他のデータクラス と統一して
Chapteのデータクラスでお願いします。
バグ修正の時に覚えていたらで大丈夫です。

2020-10-28 09:24 UTC, isimatu0612 commented on zeroschool/src/main/java/com/example/demo/repository/SectionRepository.java
> +				// 日付のフォーマットをyyyy/MM/ddに修正
これは、どこで行っていますか？
不要であれば削除をお願いします。

バグ修正の時に覚えていたらで大丈夫です。

2020-10-28 09:24 UTC, isimatu0612 commented on zeroschool/src/main/java/com/example/demo/repository/SectionRepository.java
> +	public SectionEntity selectEntity(String userNo, String courseId) {
`selectEntity`だと処理がわかりづらいので、
修正をお願いします。

バグ修正の時に覚えていたらで大丈夫です。

2020-10-28 09:24 UTC, isimatu0612 commented on zeroschool/src/main/java/com/example/demo/repository/SectionRepository.java
> +	public void addImplementation(SectionForm form) {
voidだと、登録成功 or 失敗を画面に表示できないと思いますので、
必要に応じて、戻り値の変更をお願いいたします。

バグ修正の時に覚えていたらで大丈夫です。

2020-10-28 09:24 UTC, isimatu0612 commented on zeroschool/src/main/resources/templates/section/index.html
> +	<!-- Bootstrap、CSS読み込み -->
ここでは、CSSは読み込んでいないはずです。

バグ修正の時に覚えていたらで大丈夫です。

2020-10-28 09:24 UTC, isimatu0612 approved these changes

2020-10-28 09:30 UTC, merged