テストのバグ修正を行いました。
y-o777/sche-ctrl pull request #37
Opened 2020-10-29 06:10 UTC by s-a1127

2020-10-29 06:50 UTC, isimatu0612 requested changes

2020-10-29 06:50 UTC, isimatu0612 commented on zeroschool/src/main/java/com/example/demo/controller/SectionController.java
> +			ModelAndView model, Model modelError) {
`Model modelError`は、使わずに`ModelAndView model`にセットしてください。

2020-10-29 06:50 UTC, isimatu0612 commented on zeroschool/src/main/java/com/example/demo/form/SectionForm.java
> +						return false;
エラーメッセージごとにメソッド分けを行ってください。

理由としては、以下のような感じです。
①メソッドが長い、1メソッドでいろんなことをしすぎている。
②`@AssertTrue(message = "test")`の記述ができるようになるはず。

2020-10-29 06:50 UTC, isimatu0612 commented on zeroschool/src/main/java/com/example/demo/form/SectionForm.java
>  					return false;
エラーメッセージごとにメソッド分けを行ってください。

2020-10-29 06:50 UTC, isimatu0612 commented on zeroschool/src/main/java/com/example/demo/controller/SectionController.java
> +			String errorBeforeRegisteredDate = form.getErrorBeforeRegisteredDate();
ここの処理は必要ですか？

2020-10-29 06:50 UTC, isimatu0612 commented on zeroschool/src/main/java/com/example/demo/controller/SectionController.java
> +			form.setErrorBeforeRegisteredDate(errorBeforeRegisteredDate);
ここの処理は必要ですか？

2020-10-29 06:50 UTC, isimatu0612 commented on zeroschool/src/main/java/com/example/demo/form/SectionForm.java
> +					Date afterDate = dateFormat.parse(implementationDateArray[0].replace("-", "/"));
日付のフォーマットを`yyyy-MM-dd`すれば、
`implementationDateArray[0].replace("-", "/")`この置換の処理は不要ではないでしょうか。

2020-10-29 06:50 UTC, isimatu0612 commented on zeroschool/src/main/java/com/example/demo/form/SectionForm.java
>  	// TODO 入力チェック未完成
実装が終わったら消去をお願いいたします。

2020-10-29 06:50 UTC, isimatu0612 commented on zeroschool/src/main/java/com/example/demo/repository/SectionRepository.java
> +	public SectionEntity getEntity(String userNo, String courseId) {
`getEntity　`→　`getSectionEntity`

2020-10-29 06:50 UTC, isimatu0612 commented on zeroschool/src/main/java/com/example/demo/repository/SectionRepository.java
> +				}
`if(count == 0)`は常にtrueになりそうですが、
ここの処理は必要そうですか？

不要であれば、if文とcount という変数の削除をお願いします。

2020-10-29 06:50 UTC, isimatu0612 commented on zeroschool/src/main/java/com/example/demo/repository/SectionRepository.java
別の箇所ですが、
```
85行目					// roundNoの値を変更
86行目					roundNo = result.getInt("ROUND_NO");
```

は81・82行目と処理が被っていますので不要そうです。

2020-10-29 06:50 UTC, isimatu0612 commented on zeroschool/src/main/java/com/example/demo/repository/SectionRepository.java
> +			sql += " AND b.USER_NO = ? LEFT OUTER JOIN dbo.ACTUAL_RESULTS a ON a.M_CHPATER_ID = c.ID AND a.USER_NO = ? WHERE c.M_COURSE_ID = ?";
文字列連結が多くなりそうなときは、
StringBuilderの使用を検討してください。
パフォーマンス的な問題です。

修正はお任せします。

2020-10-29 06:50 UTC, isimatu0612 commented on zeroschool/src/main/java/com/example/demo/form/SectionForm.java
> +			try {
try-catchが長すぎます。parseのとろだけでよいはずです。
長いと例外が発生している箇所を特定しづらいです。

2020-10-29 06:58 UTC, s-a1127 commented on zeroschool/src/main/java/com/example/demo/controller/SectionController.java
> +			ModelAndView model, Model modelError) {
承知しました。修正いたします。

2020-10-29 06:59 UTC, s-a1127 commented on zeroschool/src/main/java/com/example/demo/form/SectionForm.java
> +						return false;
承知しました。修正いたします。

2020-10-29 06:59 UTC, s-a1127 commented on zeroschool/src/main/java/com/example/demo/form/SectionForm.java
>  					return false;
承知しました。

2020-10-29 07:00 UTC, s-a1127 commented on zeroschool/src/main/java/com/example/demo/controller/SectionController.java
> +			String errorBeforeRegisteredDate = form.getErrorBeforeRegisteredDate();
セクション画面の表示データを取得すると、セットされていないformになってしまうので
一旦保持してから再セットするよう記述しておりました。
メソッド分けをするので添削いたします。

2020-10-29 07:01 UTC, s-a1127 commented on zeroschool/src/main/java/com/example/demo/controller/SectionController.java
> +			form.setErrorBeforeRegisteredDate(errorBeforeRegisteredDate);
セクション画面の表示データを取得すると、セットされていないformになってしまうので
一旦保持してから再セットするよう記述しておりました。
メソッド分けをするので添削いたします。

2020-10-29 07:02 UTC, s-a1127 commented on zeroschool/src/main/java/com/example/demo/form/SectionForm.java
> +					Date afterDate = dateFormat.parse(implementationDateArray[0].replace("-", "/"));
表示されている、登録済みの実施日のフォーマットがyyyy/MM/ddなので
そのデータを扱うのも兼ねてフォーマットをこのようにしておりました。
エラーメソッドを分けるので修正いたします。

2020-10-29 07:03 UTC, s-a1127 commented on zeroschool/src/main/java/com/example/demo/form/SectionForm.java
>  	// TODO 入力チェック未完成
承知しました。入力チェックが完了したら消去いたします。

2020-10-29 07:03 UTC, s-a1127 commented on zeroschool/src/main/java/com/example/demo/repository/SectionRepository.java
> +	public SectionEntity getEntity(String userNo, String courseId) {
修正いたします。

2020-10-29 07:05 UTC, s-a1127 commented on zeroschool/src/main/java/com/example/demo/repository/SectionRepository.java
> +				}
ご指摘ありがとうございます。こちらは講座ID１、Round１、chapter１の最初の目標日が欲しいので
インクリメントを別箇所に追記いたします。

2020-10-29 07:05 UTC, s-a1127 commented on zeroschool/src/main/java/com/example/demo/repository/SectionRepository.java
承知しました。確認し修正いたします。

2020-10-29 07:06 UTC, s-a1127 commented on zeroschool/src/main/java/com/example/demo/repository/SectionRepository.java
> +			sql += " AND b.USER_NO = ? LEFT OUTER JOIN dbo.ACTUAL_RESULTS a ON a.M_CHPATER_ID = c.ID AND a.USER_NO = ? WHERE c.M_COURSE_ID = ?";
承知しました。修正いたします。

2020-10-29 07:06 UTC, s-a1127 commented on zeroschool/src/main/java/com/example/demo/form/SectionForm.java
> +			try {
承知しました。ご指摘ありがとうございます。
メソッド分けを行う際に留意いたいます。

2020-10-30 05:01 UTC, isimatu0612 commented on zeroschool/src/main/java/com/example/demo/controller/SectionController.java
> +			ModelAndView model, Model modelError) {
クローズいたします。

2020-10-30 05:24 UTC, isimatu0612 commented on zeroschool/src/main/java/com/example/demo/form/SectionForm.java
> +						// 受講初日より過去の日付が入力ている場合
受講初日とは受講開始日のことですか？
yesであれば、こちらのメソッドでは使われていない気がします。

2020-10-30 05:24 UTC, isimatu0612 commented on zeroschool/src/main/java/com/example/demo/form/SectionForm.java
> +					if (!beforeDate.equals(afterDate)) {
こちらは不要そうです。
ご確認お願いいたします。

2020-10-30 05:24 UTC, isimatu0612 commented on zeroschool/src/main/java/com/example/demo/form/SectionForm.java
> +						return false;
クローズいたします。

2020-10-30 05:24 UTC, isimatu0612 commented on zeroschool/src/main/java/com/example/demo/controller/SectionController.java
> +			String errorBeforeRegisteredDate = form.getErrorBeforeRegisteredDate();
クローズいたします。

2020-10-30 05:25 UTC, isimatu0612 commented on zeroschool/src/main/java/com/example/demo/controller/SectionController.java
> +			form.setErrorBeforeRegisteredDate(errorBeforeRegisteredDate);
クローズいたします。

2020-10-30 05:26 UTC, isimatu0612 commented on zeroschool/src/main/java/com/example/demo/repository/SectionRepository.java
> +	public SectionEntity getEntity(String userNo, String courseId) {
クローズいたします。

2020-10-30 05:27 UTC, isimatu0612 commented on zeroschool/src/main/java/com/example/demo/repository/SectionRepository.java
> +				}
クローズいたします。

2020-10-30 05:28 UTC, isimatu0612 commented on zeroschool/src/main/java/com/example/demo/repository/SectionRepository.java
クローズいたします。

2020-10-30 05:28 UTC, isimatu0612 commented on zeroschool/src/main/java/com/example/demo/form/SectionForm.java
> +					Date afterDate = dateFormat.parse(implementationDateArray[0].replace("-", "/"));
クローズいたします。

2020-10-30 05:28 UTC, isimatu0612 commented on zeroschool/src/main/java/com/example/demo/form/SectionForm.java
>  	// TODO 入力チェック未完成
クローズいたします。

2020-10-30 05:29 UTC, isimatu0612 commented on zeroschool/src/main/java/com/example/demo/form/SectionForm.java
> +			try {
クローズいたします。

2020-10-30 05:29 UTC, isimatu0612 commented on zeroschool/src/main/java/com/example/demo/form/SectionForm.java
>  					return false;
クローズいたします。

2020-10-30 05:39 UTC, s-a1127 commented on zeroschool/src/main/java/com/example/demo/form/SectionForm.java
> +						// 受講初日より過去の日付が入力ている場合
ご指摘ありがとうございます。確認し修正いたします。

2020-10-30 05:41 UTC, isimatu0612 requested changes

2020-10-30 05:41 UTC, isimatu0612 commented on zeroschool/src/main/resources/templates/section/index.html
> +						style="border: none; outline: none; background-color: transparent; color: white;">戻る</a>
ボタン　→　リンクになっていますので、以下のどちらか修正をお願いいたします。
①設計書修正
②BootStrapでリンクボタンにする

2020-10-30 05:48 UTC, s-a1127 commented on zeroschool/src/main/java/com/example/demo/form/SectionForm.java
> +					if (!beforeDate.equals(afterDate)) {
if (implementationDateArray != null) {
↑ここのif文のことでしょうか。
こちらは確認しましたが、必ず要素が空文字の配列がきていたので添削しました。

implementationDateArray[0]はyyyy-MM-ddで取得されるのでreplaceをつけています。

2020-10-30 05:49 UTC, s-a1127 commented on zeroschool/src/main/resources/templates/section/index.html
> +						style="border: none; outline: none; background-color: transparent; color: white;">戻る</a>
承知しました。①を修正いたします。

2020-10-30 05:58 UTC, isimatu0612 commented on zeroschool/src/main/java/com/example/demo/form/SectionForm.java
> +					if (!beforeDate.equals(afterDate)) {
`if (!beforeDate.equals(afterDate)) {`
すみません。こちらです。

2020-10-30 06:06 UTC, isimatu0612 requested changes

2020-10-30 06:06 UTC, isimatu0612 commented on zeroschool/src/main/java/com/example/demo/form/SectionForm.java
> +	public boolean isDateAfterRegisteredDate() {
受講開始日とのチェックなので、
`isDateAfterStartDate`に変更をお願いいたします。

2020-10-30 06:06 UTC, isimatu0612 commented on zeroschool/src/main/java/com/example/demo/form/SectionForm.java
> +	public boolean isDateAfterStartDate() {
前チャプター(登録済みの日付)とのチェックなので、
`isDateAfterRegisteredDate`に変更をお願いいたします。」

2020-10-30 06:07 UTC, s-a1127 commented on zeroschool/src/main/java/com/example/demo/form/SectionForm.java
> +					if (!beforeDate.equals(afterDate)) {
ご指摘、回答いただきありがとうございます。
おっしゃる通りでした。修正いたします。

2020-10-30 06:08 UTC, s-a1127 commented on zeroschool/src/main/java/com/example/demo/form/SectionForm.java
> +	public boolean isDateAfterRegisteredDate() {
ご指摘ありがとうございます。
修正いたします。

2020-10-30 06:09 UTC, s-a1127 commented on zeroschool/src/main/java/com/example/demo/form/SectionForm.java
> +	public boolean isDateAfterStartDate() {
ご指摘ありがとうございます。
修正いたします。

2020-10-30 06:38 UTC, isimatu0612 commented on zeroschool/src/main/resources/templates/section/index.html
> +						style="border: none; outline: none; background-color: transparent; color: white;">戻る</a>
設計書を確認いたしました。
クローズいたします。

2020-10-30 06:40 UTC, isimatu0612 commented on zeroschool/src/main/java/com/example/demo/form/SectionForm.java
> +	public boolean isDateAfterRegisteredDate() {
クローズいたします。

2020-10-30 06:40 UTC, isimatu0612 commented on zeroschool/src/main/java/com/example/demo/form/SectionForm.java
> +	public boolean isDateAfterStartDate() {
クローズいたします。

2020-10-30 07:01 UTC, isimatu0612 commented on zeroschool/src/main/java/com/example/demo/form/SectionForm.java
> +						// 受講初日より過去の日付が入力ている場合
クローズいたします。

2020-10-30 07:02 UTC, isimatu0612 commented on zeroschool/src/main/java/com/example/demo/form/SectionForm.java
> +					if (!beforeDate.equals(afterDate)) {
クローズいたします。

2020-10-30 07:03 UTC, isimatu0612 commented on zeroschool/src/main/java/com/example/demo/repository/SectionRepository.java
> +			sql += " AND b.USER_NO = ? LEFT OUTER JOIN dbo.ACTUAL_RESULTS a ON a.M_CHPATER_ID = c.ID AND a.USER_NO = ? WHERE c.M_COURSE_ID = ?";
クローズいたします。

2020-10-30 07:06 UTC, merged